### ISSUE TITLE
Coding guidelines?

### ISSUE THREAD

**Issue by energy6** [damphyr/gaudi#16]
What about having some coding guidelines for Gaudi? As far as I see there are no common rules, but peeking around I found http://batsov.com/rubocop/ checking the guidelines defined in https://github.com/bbatsov/ruby-style-guide.

**Comment by damphyr** [comment]
There is a consistent coding *style* in gaudi, a couple of rules to follow when writing code:

$configuration is only accessed in a task, never in a helper method.

Methods always have system_config,platform as the last two arguments. When  the method is not platform specific then we omit platform.

The guideline for method arguments is few-to-many or simple-to-complex, with the most complex structure being the system configuration.

There is also a conscious effort to avoid mutating arguments and have the methods return whatever values are derived in a poor imitation of functional style - this has proven very useful in debugging and unit testing functionality.

Other than that, running rubocop on the code base will be an interesting exercise ;)

**Comment by damphyr** [comment]
Closing, having added doc/STYLE.md and CodeClimate analysis
